[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome6"

[[block]]
block = "music"
player = "spotify"
format = "$icon {$combo.str(max_w:20)} $play $next $prev "

[[block]]
block = "memory"
format = "$mem_used.eng(prefix:M)/$mem_total.eng(prefix:M) "

[[block]]
block = "cpu"
interval = 1
format = "\uf2db$utilization "

[[block]]
block = "load"
interval = 1
format = "$icon load avg: $1m.eng(w:4) $5m.eng(w:4) $15m.eng(w:4) "

[[block]]
block = "sound"
driver = "auto"

[[block]]
block = "battery"
interval = 10
format = "$icon $percentage $time "

[[block]]
block = "net"
device = "wlan0"
format = "$icon $ssid $signal_strength ⬇$speed_down ⬆$speed_up "
interval = 5

[[block]]
block = "time"
interval = 60
format = "$icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z')"
