theme = "gruvbox-dark"
icons = "awesome5"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
driver = "auto"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {signal_strength} {speed_down;K*b} {speed_up;K*b}"
interval = 5

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
