- name: Setup minikube network # noqa ignore-errors
  ansible.builtin.systemd:
    name: minikube-network
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
  ignore_errors: true
