# {{ ansible_managed }}

format = """
$directory\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$rust\
$jobs\
$line_break\
$character
"""

[line_break]
disabled = false

[directory]
truncate_to_repo = false
truncation_length = 10

[kubernetes]
format = "[$symbol $context](fg:33) "
disabled = false

[rust]
format = "[$symbol](red bold) "

[python]
symbol = " "
version_format = '${raw}'
format = '[(\( $symbol ${version} $virtualenv\) )]($style)'

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "
vimcmd_symbol = "[ ](bold green)"

[jobs]
symbol = " "
