- name: Install Alacritty
  community.general.pacman:
    name:
      - alacritty
    state: latest
  become: yes

- name: Create config directory
  file:
    path: ~/.config/alacritty
    state: directory

- name: Copy alcritty conf
  copy:
    src: config/alacritty/alacritty.yml
    dest: ~/.config/alacritty/alacritty.yml
