- name: Install container tools
  community.general.pacman:
    name:
      - docker
      - podman
      - buildah
      - skopeo
      - skaffold
    state: latest
  become: true

- name: Install rootless dependencies
  community.general.pacman:
    name:
      - slirp4netns # User-mode networking for containers
      - aardvark-dns #  authoritative dns server for containers
      - qemu-user-static
      - qemu-user-static-binfmt
    state: latest
  become: true

- name: /etc/subuid and /etc/subgid conf
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - src: etc/subuid
      dest: /etc/subuid
    - src: etc/subgid
      dest: /etc/subgid
  notify:
    - Podman system migrate
  become: true

- name: Create rootless config directory
  ansible.builtin.file:
    path: ~/.config/containers
    state: directory
    mode: "0755"

- name: Configure rootless storage
  ansible.builtin.copy:
    src: config/containers/storage.conf
    dest: ~/.config/containers/storage.conf
    mode: "0644"

- name: Create docker config directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: "0755"
  become: true

- name: Configure docker
  ansible.builtin.template:
    src: etc/docker/daemon.json
    dest: /etc/docker/daemon.json
    mode: "0644"
  become: true

- name: Create skaffold config directory
  ansible.builtin.file:
    path: ~/.skaffold
    state: directory
    mode: "0755"

- name: Copy skaffold config
  ansible.builtin.copy:
    src: skaffold/config
    dest: ~/.skaffold/config
    mode: "0644"

- meta: flush_handlers
  tags:
    - skip_ansible_lint
