- name: Install container tools
  community.general.pacman:
    name:
      - docker
      - podman
      - buildah
      - skopeo
      - skaffold
    state: latest
  become: yes

- name: Install rootless dependencies
  community.general.pacman:
    name:
      - slirp4netns # User-mode networking for containers
      - aardvark-dns #  authoritative dns server for containers
      - qemu-user-static
      - qemu-user-static-binfmt
    state: latest
  become: yes

- name: /etc/subuid and /etc/subgid conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest}}"
  loop:
    - src: etc/subuid
      dest: /etc/subuid
    - src: etc/subgid
      dest: /etc/subgid
  become: yes

- name: Create rootless config directory
  file:
    path: ~/.config/containers
    state: directory

- name: Configure rootless storage
  copy:
    src: config/containers/storage.conf
    dest: ~/.config/containers/storage.conf

- name: Create docker config directory
  file:
    path: /etc/docker
    state: directory
  become: yes

- name: Configure docker
  template:
    src: etc/docker/daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
  become: yes

- name: Create skaffold config directory
  file:
    path: ~/.skaffold
    state: directory

- name: Copy skaffold config
  copy:
    src: skaffold/config
    dest: ~/.skaffold/config

- meta: flush_handlers
