- name: Install docker, podman, buildah and skopeo
  community.general.pacman:
    name:
      - docker
      - podman
      - buildah
      - skopeo
    state: latest
  become: yes

- name: Install rootless dependencies
  community.general.pacman:
    name:
      - slirp4netns
    state: latest
  become: yes

- name: /etc/subuid and /etc/subgid conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest}}"
  loop:
    - src: etc/subuid
      dest: /etc/subuid
    - src: etc/subgid
      dest: /etc/subgid
  become: yes

- name: Create rootless config directory
  file:
    path: ~/.config/containers
    state: directory

- name: Configure rootless storage
  copy:
    src: config/containers/storage.conf
    dest: ~/.config/containers/storage.conf

- name: Configure docker
  template:
    src: etc/docker/daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
  become: yes

- meta: flush_handlers
