- name: Install dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - gcc
    - make
    - flex
    - git
    - bison
    - gperf
    - cmake
    - ninja
    - ccache
    - dfu-util
    - libusb
  become: yes

- name: Get ESP-IDF
  ansible.builtin.git:
    repo: https://github.com/espressif/esp-idf.git
    dest: ~/.esp
    clone: yes
    recursive: yes
    version: "v5.0"

- name: Install ESP-IDF for ESP32S3
  ansible.builtin.shell: ./install.sh esp32s3
  args:
    chdir: ~/.esp
