- name: Install esp tools
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - ldproxy
    - espup
    - espflash
  become: true

- name: Install rust toolochain
  ansible.builtin.command:
    cmd: espup install --targets esp32s3
    creates: ~/.rustup/toolchains/esp

- name: Get export-esp.sh stat
  ansible.builtin.stat:
    path: ~/export-esp.sh
  register: file

- name: Move export-esp.sh script to ~/.espup
  ansible.builtin.copy:
    src: ~/export-esp.sh
    dest: ~/.espup/export-esp.sh
    mode: preserve
    remote_src: true
  when: file.stat.exists
