- name: Install git packages
  community.general.pacman:
    name:
      - git
      - lazygit
    state: latest
  become: yes

- name: Create git config
  copy:
    src: git/gitconfig
    dest: ~/.gitconfig
    mode: 0644
