- name: Install git packages
  community.general.pacman:
    name:
      - git
      - lazygit
    state: latest
  become: true

- name: Create ~/.config/lazygit directory
  ansible.builtin.file:
    path: ~/.config/lazygit
    state: directory
    mode: "0755"

- name: Copy lazygit config
  ansible.builtin.copy:
    src: config/lazygit/config.yml
    dest: ~/.config/lazygit/config.yml
    mode: "0644"

- name: Create git config
  ansible.builtin.copy:
    src: git/gitconfig
    dest: ~/.gitconfig
    mode: "0644"
