- name: Install Go
  community.general.pacman:
    name: go
    state: latest
  become: true

- name: Install Go dev utils
  community.general.pacman:
    name:
      - gopls # lsp
      - gofumpt # formatter
      - delve # debugger
    state: latest
  become: true
