- name: Install keyd package # noqa no-changed-when
  ansible.builtin.command: yay --noconfirm --noprogressbar --cleanafter --removemake --needed --sync keyd-git

- name: Add keyd config
  ansible.builtin.copy:
    src: etc/keyd/default.conf
    dest: /etc/keyd/default.conf
    mode: "0644"
  become: true

- name: Start and enabled keyd
  ansible.builtin.systemd:
    name: keyd
    state: restarted
    enabled: true
  become: true
