- name: Common
  ansible.builtin.import_tasks: common.yaml
  tags: common

- name: Iwd
  ansible.builtin.import_tasks: wifi.yaml
  tags: wifi

- name: Install yay AUR helper
  ansible.builtin.import_tasks: yay.yaml
  tags: yay

- name: Packages
  ansible.builtin.import_tasks: packages.yaml
  tags: packages

- name: Audio
  ansible.builtin.import_tasks: audio.yaml
  tags: audio

- name: Keyboard
  ansible.builtin.import_tasks: keyboard.yaml
  tags: keyboard

- name: Git
  ansible.builtin.import_tasks: git.yaml
  tags: git

- name: Go
  ansible.builtin.import_tasks: go.yaml
  tags: go

- name: Gpu
  ansible.builtin.import_tasks: gpu.yaml
  tags: gpu

- name: Wezterm
  ansible.builtin.import_tasks: wezterm.yaml
  tags: wezterm

- name: Tmux
  ansible.builtin.import_tasks: tmux.yaml
  tags: tmux

- name: i3 # noqa: name[casing]
  ansible.builtin.import_tasks: i3.yaml
  tags: i3

- name: Lua
  ansible.builtin.import_tasks: lua.yaml
  tags: lua

- name: NeoVIM
  ansible.builtin.import_tasks: neovim.yaml
  tags: neovim

- name: Npm
  ansible.builtin.import_tasks: npm.yaml
  tags: npm

- name: Rust
  ansible.builtin.import_tasks: rust.yaml
  tags: rust

- name: Python
  ansible.builtin.import_tasks: python.yaml
  tags: python

- name: Zsh
  ansible.builtin.import_tasks: zsh.yaml
  tags: zsh

- name: Containers
  ansible.builtin.import_tasks: containers.yaml
  tags: containers

- name: Minikube
  ansible.builtin.import_tasks: minikube.yaml
  tags: minikube

- name: Dnsmasq
  ansible.builtin.import_tasks: dnsmasq.yaml
  tags: dnsmasq
  become: true

- name: Starship
  ansible.builtin.import_tasks: starship.yaml
  tags: starship

- name: Zathura
  ansible.builtin.import_tasks: zathura.yaml
  tags: zathura

- name: Esp
  ansible.builtin.import_tasks: esp.yaml
  tags: esp

- name: Bluetooth
  ansible.builtin.import_tasks: bluetooth.yaml
  tags: bluetooth
