- name: Install minikube package
  community.general.pacman:
    name: minikube
    state: latest
    update_cache: true
    executable: yay
    extra_args: --removemake --cleanafter

- name: Copy minikube-network.sh script
  ansible.builtin.template:
    src: etc/systemd/system/minikube-network.service
    dest: /etc/systemd/system/minikube-network.service
    mode: "0644"
  notify:
    - Setup minikube network
  become: true

- meta: flush_handlers
  tags:
    - skip_ansible_lint
