- name: Install neovim
  community.general.pacman:
    name: neovim
    state: latest
  become: true

- name: Copy neovim config files
  ansible.builtin.copy:
    src: config/nvim
    dest: ~/.config/
    mode: "0644"
