- name: Install npm package
  community.general.pacman:
    name: npm
    state: latest
  become: true

- name: Copy npm config file
  ansible.builtin.copy:
    src: npm/npmrc
    dest: ~/.npmrc
    mode: "0644"

- name: Install node.js packages
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop:
    - "prettier"
    - "@ansible/ansible-language-server"
    - "bash-language-server"
