- name: Upgrade the whole system
  community.general.pacman:
    upgrade: yes
    executable: yay
    update_cache: yes
    extra_args: --removemake --cleanafter

- name: Install packages
  community.general.pacman:
    name:
      - arch-audit
      - arm-none-eabi-gdb
      - bandwhich
      - base-devel
      - bat
      - bc
      - bluez-utils
      - bore # making tunnels to localhost
      - btop
      - clinfo
      - chromium
      - difftastic
      - discord
      - darktable
      - dcraw
      - dmidecode
      - dnsutils
      - dog
      - dua-cli
      - exa
      - fd
      - gcc
      - git
      - git-delta
      - github-cli
      - gping # ping with a graph
      - dua-cli # disk space usage
      - duf
      - dust
      - fakeroot
      - firefox
      - fzf
      - htop
      - hyperfine # CLI benchmarking tool
      - gimp
      - intel-compute-runtime
      - iwd
      - jless
      - jq
      - just
      - jwt-cli
      - kubeconform
      - kubectl
      - kubectx
      - kustomize
      - linux-lts
      - lrzip
      - lsof
      - lynis
      - luacheck
      - make
      - minicom
      - miniserve # CLI tool to serve files over HTTP
      - neofetch
      - nuspell
      - nmap
      - nvme-cli
      - noto-fonts
      - onefetch # Git repository summary on your terminal
      - ouch # Compressing and decompressing for various formats.
      - p7zip
      - pastel # cli to generate, analyze, convert and manipulate colors
      - pipewire-pulse
      - pkgconfig
      - powerline
      - powerline-fonts
      - procs
      - qemu-base
      - ripgrep
      - rustscan
      - screen
      - shellcheck
      - shfmt
      - skaffold
      - socat
      - stylua
      - systeroid
      - taplo-cli
      - task
      - texlive-most
      - tealdeer
      - terraform
      - tokei # Count the code
      - ttf-fira-code
      - ttf-font-awesome
      - usbutils
      - verilator
      - vlc
      - watchexec
      - which
      - xclip
      - xdg-utils
      - xorg-server
      - xsel
      - zathura-pdf-mupdf
    state: latest
    executable: yay
    update_cache: yes
    extra_args: --removemake --cleanafter

- name: Install AUR packages
  ansible.builtin.command: yay --noconfirm --noprogressbar --cleanafter --removemake --needed --sync "{{ item }}"
  loop:
    - act # Run github actions locally
    - spotify
    - slack
    - hadolint-bin

- name: Enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - iwd
  become: yes
