- name: Upgrade the whole system
  community.general.pacman:
    upgrade: true
    executable: yay
    update_cache: true
    extra_args: --removemake --cleanafter

- name: Install packages
  community.general.pacman:
    name:
      - arch-audit
      - arm-none-eabi-gdb
      - awesome-terminal-fonts
      - bandwhich
      - base-devel
      - bat
      - bc
      - bluez-utils
      - bore # making tunnels to localhost
      - btop
      - chromium
      - difftastic
      - discord
      - darktable
      - dcraw # Decoding raw photos
      - dmidecode
      - dnsutils
      - dua-cli
      - eva # A calculator REPL, similar to bc
      - eza
      - fd
      - gcc
      - git
      - git-delta
      - github-cli
      - gping # ping with a graph
      - dua-cli # disk space usage
      - duf
      - dust
      - fakeroot
      - firefox
      - fzf
      - htop
      - hyperfine # CLI benchmarking tool
      - gimp
      - iwd
      - jless
      - jq
      - just
      - jwt-cli
      - kubeconform
      - kubectl
      - kubectx
      - kustomize
      - less
      - linux
      - lrzip
      - lsof
      - lynis
      - luacheck
      - make
      - minicom
      - miniserve # Serve files over HTTP
      - mold # fast linker
      - neofetch # system information
      - nuspell
      - nmap
      - nvme-cli
      - noto-fonts
      - onefetch # Git repository summary on your terminal
      - ouch # Compressing and decompressing for various formats.
      - oxipng # PNG optimizer
      - p7zip
      - pastel # Generate, analyze, convert and manipulate colors
      - pcsclite # needed by yubikey
      - pkgconfig
      - powerline
      - powerline-fonts
      - procs
      - qemu-base
      - ripgrep
      - rustscan
      - screen
      - shellcheck
      - shellharden
      - shfmt
      - skaffold
      - sniffnet
      - socat
      - stylua
      - systeroid # Alternative to sysctl
      - swig # needed by yubikey
      - taplo-cli # TOML toolkit
      - task
      - tealdeer
      - terraform
      - tigervnc
      - tokei # Count the code
      - tree-sitter-cli
      - ttf-fira-code
      - ttf-font-awesome
      - ttf-nord-fonts
      - usbutils
      - verilator
      - viu # image viewer in the terminal
      - vlc
      - watchexec
      - which
      - xdp-tools
      - zathura-pdf-mupdf
    state: latest
    executable: yay
    update_cache: true
    extra_args: --removemake --cleanafter

- name: Install AUR packages # noqa: no-changed-when
  ansible.builtin.command: |
    yay --noconfirm --noprogressbar --cleanafter --removemake --needed --sync "{{ item }}"
  loop:
    - act # Run github actions locally
    - slack-desktop
    - hadolint-bin

- name: Install spotify tui player
  ansible.builtin.unarchive:
    src: https://github.com/aome510/spotify-player/releases/latest/download/spotify_player-x86_64-unknown-linux-gnu.tar.gz
    dest: ~/.local/bin/
    remote_src: true
    mode: "0755"
    extra_opts:
      - --transform
      - s@^spotify_player@spotify@

- name: Enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - iwd
  become: true
