- name: Install packages
  community.general.pacman:
    name:
      - act # Run github actions locally
      - arch-audit
      - bandwhich
      - base-devel
      - bat
      - bc
      - bluez-utils
      - bore # making tunnels to localhost
      - btop
      - clinfo
      - chromium
      - difftastic
      - darktable
      - dcraw
      - dmidecode
      - dnsutils
      - dog
      - dua-cli
      - exa
      - fd
      - git
      - git-delta
      - github-cli
      - google-cloud-sdk
      - gping # ping with a graph
      - duf
      - dust
      - firefox
      - fzf
      - hadolint-bin
      - hyperfine # CLI benchmarking tool
      - gimp
      - intel-compute-runtime
      - iwd
      - jq
      - just
      - jwt-cli
      - kubeconform
      - kubectl
      - kubectx
      - kustomize
      - linux-lts
      - lsof
      - lynis
      - miniserve # CLI tool to serve files over HTTP
      - neofetch
      - nuspell
      - nmap
      - nvme-cli
      - noto-fonts
      - onefetch # Git repository summary on your terminal
      - pastel # cli to generate, analyze, convert and manipulate colors
      - pipewire-pulse
      - pkgconfig
      - powerline-fonts
      - procs
      - qemu-base
      - ripgrep
      - rustscan
      - screen
      - shellcheck-bin
      - skaffold
      - slack-desktop
      - socat
      - spotify
      - systeroid
      - task
      - texlive-most
      - tealdeer
      - tokei # Count the code
      - ttf-font-awesome
      - usbutils
      - verilator
      - vlc
      - watchexec
      - xorg-server
      - xsel
      - zathura-pdf-mupdf
    state: latest
    executable: yay
    update_cache: yes
    extra_args: --removemake --cleanafter

- name: Upgrade the whole system
  community.general.pacman:
    upgrade: yes
    executable: yay
    update_cache: yes
    extra_args: --removemake --cleanafter

- name: Enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - iwd
