- name: Upgrade the whole system
  community.general.pacman:
    upgrade: true
    executable: yay
    update_cache: true
    extra_args: --removemake --cleanafter

- name: Install packages
  community.general.pacman:
    name:
      - arch-audit
      - arm-none-eabi-gdb
      - bandwhich
      - base-devel
      - bat
      - bc
      - bluez-utils
      - bore # making tunnels to localhost
      - btop
      - chromium
      - difftastic
      - discord
      - darktable
      - dcraw # Decoding raw photos
      - dmidecode
      - dnsutils
      - doggo-bin # DNS client
      - dua-cli
      - eza
      - fd
      - gcc
      - git
      - git-delta
      - github-cli
      - gping # ping with a graph
      - dua-cli # disk space usage
      - duf
      - dust
      - fakeroot
      - firefox
      - fzf
      - htop
      - hyperfine # CLI benchmarking tool
      - gimp
      - iwd
      - jless
      - jq
      - just
      - jwt-cli
      - kubeconform
      - kubectl
      - kubectx
      - kustomize
      - linux-lts
      - lrzip
      - lsof
      - lynis
      - luacheck
      - make
      - minicom
      - miniserve # Serve files over HTTP
      - neofetch # system information
      - nuspell
      - nmap
      - nvme-cli
      - noto-fonts
      - onefetch # Git repository summary on your terminal
      - ouch # Compressing and decompressing for various formats.
      - p7zip
      - pastel # Generate, analyze, convert and manipulate colors
      - pcsclite # needed by yubikey
      - pipewire-pulse
      - pkgconfig
      - powerline
      - powerline-fonts
      - procs
      - qemu-base
      - ripgrep
      - rustscan
      - screen
      - shellcheck
      - shfmt
      - skaffold
      - sniffnet
      - socat
      - stylua
      - systeroid # Alternative to sysctl
      - swig # needed by yubikey
      - taplo-cli # TOML toolkit
      - task
      - tealdeer
      - terraform
      - tigervnc
      - tokei # Count the code
      - tree-sitter-cli
      - typst
      - ttf-fira-code
      - ttf-font-awesome
      - usbutils
      - verilator
      - vlc
      - watchexec
      - which
      - zathura-pdf-mupdf
    state: latest
    executable: yay
    update_cache: true
    extra_args: --removemake --cleanafter

- name: Install AUR packages # noqa: no-changed-when
  ansible.builtin.command: yay --noconfirm --noprogressbar --cleanafter --removemake --needed --sync "{{ item }}"
  loop:
    - act # Run github actions locally
    - spotify
    - slack
    - hadolint-bin

- name: Enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - iwd
  become: true
