- name: Install pip # noqa command-instead-of-module risky-shell-pipe
  ansible.builtin.shell: curl https://bootstrap.pypa.io/get-pip.py | python - --break-system-packages
  args:
    creates: $HOME/.local/bin/pip3

- name: Create pip config dir
  ansible.builtin.file:
    path: $HOME/.config/pip
    state: directory
    mode: "0755"

- name: Configure pip
  ansible.builtin.copy:
    src: config/pip/pip.conf
    dest: ~/.config/pip/pip.conf
    mode: "0644"

- name: Install pyenv
  community.general.pacman:
    name: pyenv
    state: latest
  become: true

- name: Create $HOME/.python directory
  ansible.builtin.file:
    path: $HOME/.python
    state: directory
    mode: "0755"

- name: Install pip-tools package
  ansible.builtin.pip:
    name: pip-tools
    state: present
    extra_args: --user
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

- name: Copy packages.in
  ansible.builtin.copy:
    src: python/packages.in
    dest: $HOME/.python/packages.in
    mode: "0644"

- name: Generate python packages # noqa no-changed-when
  ansible.builtin.command: pip-compile --upgrade $HOME/.python/packages.in --output-file $HOME/.python/packages.txt --resolver=backtracking
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

- name: Install python packages
  ansible.builtin.pip:
    requirements: $HOME/.python/packages.txt
    state: present
    extra_args: --user
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

#
# Poetry
#
- name: Install Poetry
  ansible.builtin.command: pip3 install --user poetry
  args:
    creates: $HOME/.local/bin/poetry
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

- name: Create poetry config dir
  ansible.builtin.file:
    path: $HOME/.config/pypoetry
    state: directory
    mode: "0755"

- name: Copy poetry config file
  ansible.builtin.copy:
    src: config/pypoetry/config.toml
    dest: $HOME/.config/pypoetry/config.toml
    mode: "0644"

- name: Create omz completion directory
  ansible.builtin.file:
    path: $HOME/.oh-my-zsh/custom/plugins/poetry/
    state: directory
    mode: "0755"

- name: Generate completion file # noqa no-changed-when
  ansible.builtin.shell: poetry completions zsh > $HOME/.oh-my-zsh/custom/plugins/poetry/_poetry
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

#
# pdbpp
#
- name: Copy pdbpp config
  ansible.builtin.copy:
    src: python/pdbrc.py
    dest: $HOME/.pdbrc.py
    mode: "0644"

#
# ruff
#
- name: Create ruff config dir
  ansible.builtin.file:
    path: $HOME/.config/ruff
    state: directory
    mode: "0755"

- name: Copy ruff config
  ansible.builtin.copy:
    src: config/ruff/pyproject.toml
    dest: $HOME/.config/ruff/pyproject.toml
    mode: "0644"
