- name: Install rustup & rust-analyzer
  community.general.pacman:
    name:
      - rustup
      - rust-analyzer
    state: latest
  become: yes

- name: Install the stable toolchain
  shell: rustup default stable

- name: Install components
  shell: rustup component add rust-src clippy rustfmt

- name: Add cargo subcommands
  community.general.pacman:
    name: "{{ item }}"
  loop:
    - cargo-deny
    - cargo-edit
    - cargo-generate
    - cargo-nextest
    - sccache
  become: yes

- name: Create cargo config directory
  file:
    path: ~/.cargo
    state: directory

- name: Add cargo config
  copy:
    content: |
      [build]
      rustc-wrapper = "sccache"
    dest: ~/.cargo/config
  tags:
    - config-rust
