- name: Install rustup & rust-analyzer
  community.general.pacman:
    name:
      - rustup
      - rust-analyzer
    state: latest
  become: true

- name: Install the stable toolchain
  ansible.builtin.command: rustup default stable
  changed_when: true

- name: Install components
  ansible.builtin.command: rustup component add rust-src clippy rustfmt
  changed_when: true

- name: Add cargo subcommands
  community.general.pacman:
    name: "{{ item }}"
  loop:
    - cargo-deny
    - cargo-edit
    - cargo-generate
    - cargo-nextest
    - sccache
  become: true

- name: Create cargo config directory
  ansible.builtin.file:
    path: ~/.cargo
    state: directory
    mode: "0755"

- name: Add cargo config
  ansible.builtin.copy:
    content: |
      [build]
      rustc-wrapper = "sccache"
    dest: ~/.cargo/config
    mode: "0644"
