- name: Install rust toolchain
  shell: curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y

- name: Install rust-src
  shell: PATH=$HOME/.cargo/bin:$PATH rustup component add rust-src

- name: Install rust-analyzer
  community.general.pacman:
    name: rust-analyzer
    state: latest
  become: yes

- name: Add cargo subcommands
  community.general.pacman:
    name: "{{ item }}"
  loop:
    - cargo-deny
    - cargo-edit
    - cargo-generate
    - cargo-nextest
    - sccache
  become: yes

- name: Add cargo config
  copy:
    content: |
      [build]
      rustc-wrapper = "sccache"
    dest: ~/.cargo/config
  tags:
    - config-rust
