- name: Install starship package
  community.general.pacman:
    name: starship
    state: latest
  become: true

- name: Create config directory
  ansible.builtin.file:
    path: ~/.config/starship
    state: directory
    mode: "0755"

- name: Copy config file
  ansible.builtin.copy:
    src: config/starship/config.toml
    dest: ~/.config/starship/config.toml
    mode: "0644"
