- name: Install tmux binary
  ansible.builtin.package:
    name: tmux
    state: latest
  become: yes

- name: Install tmux plugins dependencies
  ansible.builtin.package:
    name:
      - gawk
      - xsel
      - xclip
      - fzf
    state: latest
  become: yes

- name: Create ~/.config/tmux directory
  file:
    path: ~/.config/tmux
    state: directory

- name: Install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Copy Tmux config file
  copy:
    src: config/tmux/tmux.conf
    dest: ~/.config/tmux/tmux.conf

- name: Copy Tmux status file
  copy:
    src: config/tmux/tmux-status.conf
    dest: ~/.config/tmux/tmux-status.conf

- name: Install plugins
  shell: ~/.tmux/plugins/tpm/bin/install_plugins
  environment:
    TMUX_PLUGIN_MANAGER_PATH: $HOME/.tmux/plugins/

- name: Clean plugins
  shell: ~/.tmux/plugins/tpm/bin/clean_plugins
  environment:
    TMUX_PLUGIN_MANAGER_PATH: $HOME/.tmux/plugins/

- name: Update plugins
  shell: ~/.tmux/plugins/tpm/bin/update_plugins all
  environment:
    TMUX_PLUGIN_MANAGER_PATH: $HOME/.tmux/plugins/
