- name: Install wezterm
  community.general.pacman:
    name:
      - wezterm
    state: latest
  become: true

- name: Create config directory
  ansible.builtin.file:
    path: ~/.config/wezterm
    state: directory
    mode: "0755"

- name: Copy wezterm conf
  ansible.builtin.copy:
    src: config/wezterm/wezterm.lua
    dest: ~/.config/wezterm/wezterm.lua
    mode: "0644"
