- name: Install iwd
  community.general.pacman:
    name: iwd
    state: latest
  become: true

- name: Create iwd config dir
  ansible.builtin.file:
    path: /etc/iwd
    state: directory
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Copy iwd config
  ansible.builtin.copy:
    src: etc/iwd/main.conf
    dest: /etc/iwd/main.conf
    mode: "0644"
  notify:
    - Restart iwd
  become: true

- name: Enable iwd service
  ansible.builtin.systemd:
    name: iwd
    enabled: true
    state: started
  become: true
