- name: Install zathura
  community.general.pacman:
    name: zathura
    state: latest
    executable: yay
    update_cache: true
    extra_args: --removemake --cleanafter

- name: Create config directory
  ansible.builtin.file:
    path: ~/.config/zathura
    state: directory
    mode: "0755"

- name: Copy zathura conf
  ansible.builtin.copy:
    src: config/zathura/zathurarc
    dest: ~/.config/zathura/zathurarc
    mode: "0644"
