- name: Install docker package
  community.general.pacman:
    name: docker
    state: latest

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes

- name: Create /etc/docker directory
  file:
    path: /etc/docker
    state: directory

- name: Copy docker daemon conf
  template:
    src: etc/docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    mode: 0644
  notify:
    - restart docker

- meta: flush_handlers
