- name: Packages
  include: packages.yaml
  tags: packages

- name: Git
  include: git.yaml
  tags: git

- name: Alacritty
  include: alacritty.yaml
  tags: alacritty

- name: Tmux
  include: tmux.yaml
  tags: tmux

- name: i3
  include: i3.yaml
  tags: i3

- name: NeoVIM
  include: neovim.yaml
  tags: neovim

- name: Npm
  include: npm.yaml
  tags: npm

- name: Rust
  include: rust.yaml
  tags: rust

- name: Python
  include: python.yaml
  tags: python

- name: Zsh
  include: zsh.yaml
  tags: zsh

- name: Docker
  include: docker.yaml
  tags: docker
  become: yes

- name: minikube
  include: minikube.yaml
  tags: minikube
