- name: Install packages
  community.general.pacman:
    name:
      - alsa-utils
      - bat
      - bc
      - chromium
      - exa
      - darktable
      - git-delta
      - duf
      - dust
      - fd
      - firefox
      - fzf
      - gimp
      - jq
      - minikube
      - mupdf
      - nvme-cli
      - noto-fonts
      - powerline-fonts
      - pulseaudio-alsa
      - procs
      - ripgrep
      - tldr
      - ttf-font-awesome
      - vlc
      - watchexec
      - wpa_supplicant
      - xsel
    state: latest
  become: yes
