- name: Install packages
  community.general.pacman:
    name:
      - alsa-utils
      - bat
      - bc
      - bluez-utils
      - chromium
      - exa
      - darktable
      - git-delta
      - duf
      - dust
      - fd
      - firefox
      - fzf
      - gimp
      - jq
      - kubectl
      - kubectx
      - kustomize
      - minikube
      - mupdf
      - nmap
      - nvme-cli
      - noto-fonts
      - powerline-fonts
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - procs
      - ripgrep
      - shellcheck
      - skaffold
      - texlive-most
      - tldr
      - ttf-font-awesome
      - vlc
      - watchexec
      - wpa_supplicant
      - xsel
    state: latest
  become: yes

- name: Download from github
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 755
  loop:
    - src: https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
      dest: ~/bin/hadolint
