- name: Install packages
  community.general.pacman:
    name:
      - base-devel
      - bat
      - bc
      - bluez-utils
      - chromium
      - exa
      - darktable
      - dcraw
      - dmidecode
      - dnsutils
      - git
      - git-delta
      - github-cli
      - google-cloud-sdk
      - duf
      - dust
      - fd
      - firefox
      - fzf
      - hadolint-bin
      - gimp
      - htop
      - iwd
      - jq
      - kubectl
      - kubectx
      - kustomize
      - kubeval-bin
      - linux-lts
      - lsof
      - lynis
      - mupdf
      - nmap
      - nvme-cli
      - noto-fonts
      - pipewire-pulse
      - powerline-fonts
      - procs
      - ripgrep
      - shellcheck
      - skaffold
      - slack-desktop
      - socat
      - spotify
      - task
      - texlive-most
      - tealdeer
      - ttf-font-awesome
      - usbutils
      - vlc
      - watchexec
      - xorg-server
      - xsel
    state: latest
    executable: yay
    update_cache: yes
    extra_args: --removemake --cleanafter

- name: Upgrade the whole system
  community.general.pacman:
    upgrade: yes
    executable: yay
    update_cache: yes
    extra_args: --removemake --cleanafter

- name: Enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - iwd
